### PR TITLE
Enable Skills to work with Statue of Uncertainty

### PR DESCRIPTION
**Pull request by drbirbdev**
Tested with minimal other mods installed.  Not sure how stuff like Walk of Life would function with this change, so it's probably worth testing that next.

### CODE REVIEW

**Comment by spacechase0** [comment]
I feel like this feature needs something important: A `virtual DoImmediateProfessionPerk() {}` function as part of `Skills.Skill.Profession` which is called when a profession is undone. Do you want to add this or should I?

**Comment by spacechase0** [comment]
Also I'm unsure about setting the transpiles to happen after Walk of Life. Since Walk of Life changes a bunch of these things too, it might make it difficult for DaLion to make changes taking ours into account? I'm unsure, I probably need to ask about them about that.

**Comment by drbirbdev** [comment]
Priority was set after WoL at DaLions suggestion 
https://discordapp.com/channels/137344473976799233/156109690059751424/1029152155266973696

It's not immediately obvious to me how DoImmediateProfessionPerk() would be used.  Is it to like undo custom state that a profession sets as part of being obtained?

**Comment by spacechase0** [comment]
Oh, I forgot to change the function name when I copy pasted it. `DoImmediateProfessionPerk`, it's `UndoImmediateProfessionPerk` that should exist. A good example is the level 5 combat perk Fighter which gives +15 HP.

**Comment by drbirbdev** [comment]
Yeah, this makes sense with the example.  If you are willing to add that I'd welcome it, otherwise I'll try to do so at some point.

**Pull request merged**
