### PR TITLE
Fix GenericModConfigMenu for mobile

### PR DESCRIPTION
**Pull request by ZaneYork**
1. `Mouse.GetState().LeftButton` does not work in mobile platform, use `Game1.input.GetMouseState().LeftButton` instead

### CODE REVIEW

**Comment by ellipszist** [comment]
Drop-down list cannot be selected.

https://github.com/spacechase0/StardewValleyMods/assets/43781364/1af0f9cd-efb4-407c-aaf9-1143effae715

**Comment by spacechase0** [comment]
@ellipszist Did you try dragging your finger? Judging from the code that might work?

**Comment by ellipszist** [comment]
> @ellipszist Did you try dragging your finger? Judging from the code that might work?
It works.
https://github.com/spacechase0/StardewValleyMods/assets/43781364/464e4bd4-b425-4a0b-815e-e6b28d75f39a

**Comment by ellipszist** [comment]
@spacechase0 It works.

https://github.com/spacechase0/StardewValleyMods/assets/43781364/41da340d-e85b-4322-89a2-929e8f677633

**Comment by hjkl5588009** [comment]
> 

In fact, it's just a repair request, and it hasn't changed yet

**Comment by hjkl5588009** [comment]
> 

In fact, it's just a repair request, and it hasn't changed yet

**Comment by ZaneYork** [comment]
> Drop-down list cannot be selected.
> 
>  SVID_20230712_105602_1.mp4

Press down to activate drop-down menu (do not release your finger), drag to the menu item you want to select, release to confirm

**Pull request merged**
