### PR TITLE
Add or update Spanish Translations for Bug Net, Capstone Professions, Displays, Magic, More Rings, Preexisting Relationships, and Surfing Festival

### PR DESCRIPTION
**Pull request by ghost**
Added and completed the spanish translations for all the i18n compatible mods.

<3

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! Is this translation in Displays incomplete though?
```js
"mannequin.name.magic-female": "Maniqu"
```

**Comment by Evelyon** [comment]
> Thanks! Is this translation in Displays incomplete though?
> ```js
> "mannequin.name.magic-female": "Maniqu"
> ```

Whoops, i'll fix that in a moment

**Comment by Evelyon** [comment]
Ok i fixed it

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks for all the help! Merged into `develop` for the upcoming Bug Net 1.4.0, Capstone Professions 1.0.5, Displays 1.0.4, Magic 0.5.6, More Rings 1.1.4, Preexisting Relationships 1.0.3, and Surfing Festival 1.0.11.

**Pull request merged**
